import * as fs from "node:fs";
import * as path from "node:path";
import type { TestHome } from "./test-home.js";

/** Minimal Node project layout: enough structure for the E2E suite to
 *  not crash on `ls`, small enough that the lifecycle stays fast. */
export function makeMinimalProjectFiles(): Array<{ path: string; content: string }> {
	return [
		{
			path: "package.json",
			content: JSON.stringify({
				name: "pi-velpari-e2e-fixture",
				version: "0.0.0",
				type: "module",
				private: true,
			}, null, 2) + "\n",
		},
		{
			path: "README.md",
			content: "# E2E fixture\n\nA minimal Node project for Pi-Velpari E2E tests.\n",
		},
		{ path: "src/index.js", content: "export const hello = () => 'hi';\n" },
	];
}

/** Write a valid `.pi/velpari/files.json` so the doctor and view
 *  commands have a projectName to read. Matches the v3 shape defined
 *  in `pi-extension/src/config.ts`. */
export function seedVelpariConfig(
	home: TestHome,
	opts: { projectName?: string } = {},
): void {
	const cfgDir = path.join(home.cwd, ".pi", "velpari");
	fs.mkdirSync(cfgDir, { recursive: true });
	const projectName = opts.projectName ?? "E2EFixture";
	const value = {
		_comment: "Generated by E2E fixture.",
		version: 3,
		projectName,
		framework: { language: "typescript", runtime: "node" },
		inputDocuments: ["README.md"],
		outputPaths: {},
		excludedPaths: [".git/", "node_modules/", "dist/"],
	};
	fs.writeFileSync(path.join(cfgDir, "files.json"), JSON.stringify(value, null, 2) + "\n", "utf8");
}
