import * as fs from "node:fs";
import * as path from "node:path";
import type { TestHome } from "./test-home.js";
import { DEFAULT_EXCLUDED_PATHS } from "../../../src/core/config.js";

/** Minimal Node project layout: enough structure for the E2E suite to
 *  not crash on `ls`, small enough that the lifecycle stays fast. */
export function makeMinimalProjectFiles(): Array<{ path: string; content: string }> {
	return [
		{
			path: "package.json",
			content:
				JSON.stringify(
					{
						name: "pi-velpari-e2e-fixture",
						version: "0.0.0",
						type: "module",
						private: true,
					},
					null,
					2,
				) + "\n",
		},
		{
			path: "README.md",
			content: "# E2E fixture\n\nA minimal Node project for Pi-Velpari E2E tests.\n",
		},
		{ path: "src/index.js", content: "export const hello = () => 'hi';\n" },
	];
}

/** Write a valid v4 `.pi/velpari/files.json` so the doctor and view
 *  commands have a projectName to read. Matches the v4 shape defined
 *  in `pi-extension/src/core/config.ts` — defaults are imported from
 *  the source module so fixture and code never drift. */
export function seedVelpariConfig(home: TestHome, opts: { projectName?: string } = {}): void {
	const cfgDir = path.join(home.cwd, ".pi", "velpari");
	fs.mkdirSync(cfgDir, { recursive: true });
	const projectName = opts.projectName ?? "E2EFixture";
	const value = {
		_comment: "Generated by E2E fixture.",
		version: 4,
		projectName,
		framework: { language: "typescript", runtime: "node" },
		inputDocuments: ["README.md"],
		outputPaths: {},
		codePaths: ["src/"],
		testPaths: ["test/"],
		excludedPaths: [...DEFAULT_EXCLUDED_PATHS],
	};
	fs.writeFileSync(path.join(cfgDir, "files.json"), JSON.stringify(value, null, 2) + "\n", "utf8");
}

/** Write a legacy v3 `.pi/velpari/files.json`. Used by the migration
 *  e2e test — `loadFilesConfig` must upgrade it to v4 on load. */
export function seedVelpariConfigV3(home: TestHome, opts: { projectName?: string } = {}): void {
	const cfgDir = path.join(home.cwd, ".pi", "velpari");
	fs.mkdirSync(cfgDir, { recursive: true });
	const projectName = opts.projectName ?? "E2EFixture";
	const value = {
		_comment: "Generated by E2E fixture (legacy v3).",
		version: 3,
		projectName,
		framework: { language: "typescript", runtime: "node" },
		inputDocuments: ["README.md"],
		outputPaths: {},
		excludedPaths: [".git/", "node_modules/", "dist/"],
	};
	fs.writeFileSync(path.join(cfgDir, "files.json"), JSON.stringify(value, null, 2) + "\n", "utf8");
}
