/**
 * Generated-files check — Phase C (G4), Doctor v2.
 *
 * Audit of generated files against `.pi/velpari/generated-manifest.json`
 * (the sha256 manifest the sub-agent generator maintains — verified at
 * planning: no other doctor check reads it; role/frontmatter/footer
 * audits live in `checks/sub-agent-generator.ts` + `checks/agents.ts`,
 * this check is the integrity layer over the manifest).
 *
 *   - manifest file exists but loader returned empty → `warning generated-manifest-unreadable`
 *     (the loader is fail-open by design — corrupt JSON looks empty);
 *   - empty manifest + no tracked files → one `info`;
 *   - per entry: file gone → **`error`** `generated-file-missing`;
 *     sha256 mismatch → **`warning`** `generated-file-modified`;
 *     generated AGENT `.md` with missing/bad frontmatter → **`error`**
 *     `generated-file-bad-config` (REQUIRED_AGENT_FIELDS from `checks/agents.ts`);
 *   - reverse scan of `.pi/agents/*.md`: footer `_Generated by pi-velpari
 *     (generator v<N>)_` present but file absent from the manifest →
 *     **`warning`** `generated-file-unregistered`;
 *   - all good → one `ok`.
 *
 * Read-only; whole function try/catch-wrapped (doctor ALWAYS renders).
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { hashFileContent } from "../../core/fingerprints.js";
import { getGeneratedManifestPath, loadGeneratedManifest } from "../../core/generated-manifest.js";
import type { DiagnosticItem, DiagnosticSection } from "../_types.js";
import { REQUIRED_AGENT_FIELDS, parseFrontmatter } from "./agents.js";
import { suggestionFor } from "./fix-suggestions.js";

/** Section title (stable — tests key on it). */
const SECTION_TITLE = "Newly generated files (generated-manifest validation)";

/** Mirrors `checks/sub-agent-generator.ts` — footer marker on generated agents. */
const GENERATOR_FOOTER_RE = /_Generated by pi-velpari \(generator v(\d+)\)/;

/** True for generated AGENT files (frontmatter-contract subjects). */
function isGeneratedAgentPath(relPath: string): boolean {
	return relPath.split("\\").join("/").includes(".pi/agents/") && relPath.endsWith(".md");
}

/**
 * Build the "Newly generated files" section (read-only).
 * @param {string} cwd - Project root.
 * @returns {DiagnosticSection} One section; missing manifest is `info`, integrity findings are `error`/`warning`.
 */
export function checkGeneratedFilesSection(cwd: string): DiagnosticSection {
	const items: DiagnosticItem[] = [];
	try {
		const manifestPath = getGeneratedManifestPath(cwd);
		const manifestExists = existsSync(manifestPath);
		const manifest = loadGeneratedManifest(cwd);
		const entries = Object.entries(manifest.files);

		if (manifestExists && entries.length === 0) {
			// Loader is fail-open: a file ON DISK that parses to empty means
			// corrupt JSON or wrong shape.
			items.push({
				status: "warning",
				message:
					"generated-manifest-unreadable: .pi/velpari/generated-manifest.json exists but is corrupt or wrong-shaped (loader returned empty).",
				suggestion: suggestionFor("generated-manifest-unreadable"),
			});
		}

		if (entries.length === 0 && items.length === 0) {
			items.push({
				status: "info",
				message: "No generated files tracked yet — run /velpari-generate-sub-agents to create project sub-agents.",
			});
		}

		let findings = items.length > 0;
		for (const [relPath, expectedSha] of entries) {
			const abs = join(cwd, relPath);
			if (!existsSync(abs)) {
				findings = true;
				items.push({
					status: "error",
					message: `generated-file-missing: ${relPath} is in the manifest but no longer exists on disk.`,
					suggestion: suggestionFor("generated-file-missing"),
				});
				continue;
			}

			const current = hashFileContent(abs);
			if (current !== expectedSha) {
				findings = true;
				items.push({
					status: "warning",
					message: `generated-file-modified: ${relPath} changed since it was generated.`,
					details: [
						`manifest sha256: ${expectedSha.slice(0, 16)}…`,
						`current  sha256: ${(current ?? "unreadable").slice(0, 16)}…`,
					],
					suggestion: suggestionFor("generated-file-modified"),
				});
			}

			if (isGeneratedAgentPath(relPath)) {
				try {
					const fm = parseFrontmatter(readFileSync(abs, "utf8"));
					const missing = REQUIRED_AGENT_FIELDS.filter((f) => !fm[f]);
					if (missing.length > 0) {
						findings = true;
						items.push({
							status: "error",
							message: `generated-file-bad-config: ${relPath} has missing/invalid frontmatter field(s): ${missing.join(", ")}.`,
							suggestion: suggestionFor("generated-file-bad-config"),
						});
					}
				} catch {
					findings = true;
					items.push({
						status: "error",
						message: `generated-file-bad-config: ${relPath} cannot be read for frontmatter validation.`,
						suggestion: suggestionFor("generated-file-bad-config"),
					});
				}
			}
		}

		// Reverse scan: footer-marked agents the manifest does not track.
		const agentsDir = join(cwd, ".pi", "agents");
		if (existsSync(agentsDir)) {
			try {
				const tracked = new Set(entries.map(([rel]) => rel.split("\\").join("/")));
				for (const name of readdirSync(agentsDir)) {
					if (!name.endsWith(".md")) continue;
					const rel = `.pi/agents/${name}`;
					if (tracked.has(rel)) continue;
					let text = "";
					try {
						text = readFileSync(join(agentsDir, name), "utf8");
					} catch {
						continue;
					}
					if (GENERATOR_FOOTER_RE.test(text)) {
						findings = true;
						items.push({
							status: "warning",
							message: `generated-file-unregistered: ${rel} carries the generator footer but is absent from the manifest.`,
							suggestion: suggestionFor("generated-file-unregistered"),
						});
					}
				}
			} catch {
				/* unreadable agents dir — skip reverse scan */
			}
		}

		if (!findings && entries.length > 0) {
			items.push({
				status: "ok",
				message: `${entries.length} generated file(s) verified against the manifest.`,
			});
		}
	} catch (err) {
		items.push({
			status: "warning",
			message: `generated-files check skipped (${(err as Error)?.message ?? String(err)})`,
		});
	}
	return { title: SECTION_TITLE, items };
}
