/**
 * Sub-agent generator completeness check (Phase 7; generator v2 scope).
 *
 * Surfaces the health of every sub-agent `/velpari-generate-sub-agents`
 * can ship — all roles across the 4 generation phases
 * (`core/agents-config.ts:GENERATION_PHASES`), not only the brainstorm
 * four.
 *
 * For each generatable role:
 *
 *   1. Resolve the effective agent name through `.pi/velpari/agents.json`
 *      (identity when absent).
 *   2. If the resolved name is the bundled default (`<role>`) → the
 *      bootstrap path covers it. Info item.
 *   3. If the resolved name is a custom mapping (not the default, not
 *      `<slug>-<role>`) → the user owns it. Info item; integrity
 *      checks live in `checkAgentFileIntegrity`.
 *   4. If the resolved name matches `<slug>-<role>` → it's a generated
 *      agent. Check:
 *      a. File exists on disk.
 *      b. Frontmatter `name:` matches the filename stem.
 *      c. Footer carries `_Generated by pi-velpari (generator v<N>)_`
 *         with `N >= GENERATOR_VERSION`. A footer with `N < CURRENT` is
 *         a STALE warning (regen recommended). No footer is an error
 *         (file claims to be generated but lost the marker).
 *
 * A project-wide "stale-version" pass also walks every `.pi/agents/*.md`
 * with a footer carrying `N < GENERATOR_VERSION` and reports a single
 * warning per stale file — even ones NOT registered as generatable roles
 * (e.g. hand-copied agents shipped earlier).
 *
 * Layer 1 (doctor). Imports only `node:*`, same-layer doctor modules,
 * and L0 `core/` modules. Never imports upward to ops/, ui/, hooks/,
 * commands/.
 */

import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import type { DiagnosticItem, DiagnosticSection } from "../_types.js";
import { suggestionFor } from "./fix-suggestions.js";
import { GENERATOR_VERSION, getProjectSlug } from "../../core/agents-generator.js";
import {
	DEFAULT_AGENTS,
	GENERATION_PHASES,
	loadAgentConfig,
	resolveAgentName,
	type AgentConfig,
	type GenerationPhase,
	type VelpariRole,
} from "../../core/agents-config.js";

/** Matches the footer `_Generated by pi-velpari (generator v<N>)..._`.
 *  Tolerant: the footer is followed by either ` from canonical body
 *  file: <bodyFile>._` (canonical-body roles) or
 *  ` from technology resource(s): \`<id>\`._` (standard roles).
 *  We capture only the version number and ignore the suffix. */
const GENERATOR_FOOTER_RE = /_Generated by pi-velpari \(generator v(\d+)\)/;

/** Compute the expected generated agent name for a role given a slug. */
function generatedName(slug: string, role: string): string {
	return `${slug}-${role}`;
}

/**
 * Read agents.json defensively. On any failure, return null (the
 * orchestrator treats absence as "all defaults").
 */
function readAgentConfig(cwd: string): AgentConfig | null {
	try {
		return loadAgentConfig(cwd);
	} catch {
		return null;
	}
}

/** Per-role completeness check. */
function checkRoleAgent(cwd: string, slug: string, config: AgentConfig | null, role: string): DiagnosticItem[] {
	const items: DiagnosticItem[] = [];
	const resolved = resolveAgentName(config, role as VelpariRole);
	const expectedGenerated = generatedName(slug, role);

	if (resolved === DEFAULT_AGENTS[role as VelpariRole]) {
		// Bundled default — bootstrap path covers it. No generated-agent
		// assertion applies. Inform only.
		items.push({
			status: "info",
			message: `${role}: bundled default (${DEFAULT_AGENTS[role as VelpariRole]}.md) — run /velpari-generate-sub-agents to produce a project-specific copy.`,
		});
		return items;
	}

	if (resolved !== expectedGenerated) {
		// Custom mapping — user owns this agent. The general integrity
		// check (checkAgentFileIntegrity) covers its frontmatter + tools.
		items.push({
			status: "info",
			message: `${role}: custom mapping (${resolved}.md) — user-provided; integrity not asserted here.`,
		});
		return items;
	}

	// Generated agent — strict checks.
	const filePath = join(cwd, ".pi", "agents", `${resolved}.md`);
	if (!existsSync(filePath)) {
		items.push({
			status: "error",
			message: `${resolved}.md (${role}) MISSING — agents.json maps to a generated name whose file is absent.`,
			suggestion: suggestionFor("scout-agent-missing"),
		});
		return items;
	}

	const content = readFileSync(filePath, "utf8");
	const stem = resolved;

	// Frontmatter name matches filename.
	const fmMatch = content.match(/^---\n([\s\S]*?)\n---/);
	if (!fmMatch) {
		items.push({
			status: "error",
			message: `${resolved}.md (${role}) has no YAML frontmatter block.`,
		});
		return items;
	}
	const nameLine = fmMatch[1]!.match(/^name:\s*(.+)$/m);
	if (!nameLine || nameLine[1]!.trim() !== stem) {
		items.push({
			status: "error",
			message: `${resolved}.md (${role}) frontmatter \`name:\` does not match filename "${stem}".`,
			suggestion: "Regenerate via /velpari-generate-sub-agents (the generator always writes matching frontmatter).",
		});
		return items;
	}

	// Footer version match.
	const footerMatch = content.match(GENERATOR_FOOTER_RE);
	if (!footerMatch) {
		items.push({
			status: "error",
			message: `${resolved}.md (${role}) is missing the generator-version footer (expected v${GENERATOR_VERSION}).`,
			suggestion: suggestionFor("scout-agent-missing"),
		});
		return items;
	}
	const fileVersion = parseInt(footerMatch[1]!, 10);
	if (Number.isNaN(fileVersion)) {
		items.push({
			status: "error",
			message: `${resolved}.md (${role}) carries an unreadable generator version ("${footerMatch[1]!}").`,
		});
		return items;
	}
	if (fileVersion < GENERATOR_VERSION) {
		items.push({
			status: "warning",
			message: `${resolved}.md (${role}) is stale (v${fileVersion}); current generator is v${GENERATOR_VERSION}.`,
			suggestion: `Run /velpari-generate-sub-agents to refresh. The manifest's sha256 will keep your edits in keptDrifted; the 3 standard sections + footer will be updated.`,
		});
		return items;
	}
	if (fileVersion > GENERATOR_VERSION) {
		items.push({
			status: "info",
			message: `${resolved}.md (${role}) carries a NEWER generator version (v${fileVersion}) than the running extension (v${GENERATOR_VERSION}); likely a future-Velpari install.`,
		});
		return items;
	}
	items.push({
		status: "ok",
		message: `${resolved}.md (${role}) generator v${GENERATOR_VERSION} OK.`,
	});
	return items;
}

/** Project-wide scan for files with a stale generator-version footer.
 *  Skips files already flagged by the per-role loop (dedup via `exclude`)
 *  so the summary count is not inflated. */
function scanStaleVersions(cwd: string, exclude: ReadonlySet<string>): DiagnosticItem[] {
	const items: DiagnosticItem[] = [];
	const agentsDir = join(cwd, ".pi", "agents");
	if (!existsSync(agentsDir)) return items;

	const files = readdirSync(agentsDir, { encoding: "utf8" }).filter(
		(name) => typeof name === "string" && name.endsWith(".md"),
	);

	for (const filename of files) {
		if (exclude.has(filename)) continue; // dedup against per-role loop
		const filePath = join(agentsDir, filename);
		const content = readFileSync(filePath, "utf8");
		const match = content.match(GENERATOR_FOOTER_RE);
		if (!match) continue;
		const fileVersion = parseInt(match[1]!, 10);
		if (Number.isNaN(fileVersion)) continue;
		if (fileVersion < GENERATOR_VERSION) {
			items.push({
				status: "warning",
				message: `${filename} is stale (v${fileVersion} < v${GENERATOR_VERSION}).`,
				suggestion: `Run /velpari-generate-sub-agents to refresh.`,
			});
		}
	}
	return items;
}

/** Every role the generator can produce, in phase order (P1 → P4),
 *  deduplicated. Derived from GENERATION_PHASES — never hand-copied. */
function allGeneratableRoles(): string[] {
	const seen = new Set<string>();
	const roles: string[] = [];
	for (const phase of [1, 2, 3, 4] as readonly GenerationPhase[]) {
		for (const role of GENERATION_PHASES[phase].roles) {
			if (seen.has(role)) continue;
			seen.add(role);
			roles.push(role);
		}
	}
	return roles;
}

/** Doctor section "Sub-agent generator completeness". */
export function checkSubAgentGeneratorSection(cwd: string): DiagnosticSection {
	const items: DiagnosticItem[] = [];
	const config = readAgentConfig(cwd);
	const slug = getProjectSlug(cwd);
	const generatableRoles = allGeneratableRoles();

	// Track files already flagged by the per-role loop so the project-wide
	// scan doesn't double-count stale files for registered roles.
	const alreadyFlagged = new Set<string>();
	for (const role of generatableRoles) {
		const roleItems = checkRoleAgent(cwd, slug, config, role);
		items.push(...roleItems);
		for (const item of roleItems) {
			if (item.status === "warning" || item.status === "error") {
				const m = item.message.match(/^([^\s:]+\.md)/);
				if (m) alreadyFlagged.add(m[1]!);
			}
		}
	}

	items.push(...scanStaleVersions(cwd, alreadyFlagged));

	const errorCount = items.filter((i) => i.status === "error").length;
	const warningCount = items.filter((i) => i.status === "warning").length;
	items.push({
		status: errorCount === 0 ? (warningCount === 0 ? "ok" : "info") : "info",
		message: `Sub-agent generator summary: ${generatableRoles.length} role(s) across 4 generation phase(s) checked (current generator v${GENERATOR_VERSION}); ${errorCount} error(s), ${warningCount} warning(s).`,
	});

	return { title: "Sub-agent generator completeness", items };
}
