/**
 * Doctor check: Sub-agent generator completeness (Phase 7).
 *
 * Covers every bucket:
 *   - bundled default (no agents.json) — info per role
 *   - custom mapping — info per role
 *   - generated-agent missing file — error
 *   - generated-agent present with matching frontmatter + current footer — ok
 *   - generated-agent stale footer (v < current) — warning
 *   - generated-agent newer footer (v > current) — info
 *   - generated-agent frontmatter name mismatch — error
 *   - generated-agent missing footer — error
 *   - project-wide scan catches stale files for non-registered roles
 *   - section summary line tracks errors/warnings
 */

import { describe, it } from "node:test";
import { strict as assert } from "node:assert";
import {
	mkdirSync,
	mkdtempSync,
	readFileSync,
	rmSync,
	writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { checkSubAgentGeneratorSection } from "../../src/doctor/checks/sub-agent-generator.js";
import { GENERATOR_VERSION } from "../../src/core/agents-generator.js";
import {
	VELPARI_BRAINSTORM_GENERATED_ROLES,
} from "../../src/core/agents-config.js";

function freshTmp(): string {
	return mkdtempSync(join(tmpdir(), "velpari-doctor-"));
}

/** Write a generated-style agent file with the given generator version. */
function writeGeneratedAgent(
	cwd: string,
	agentName: string,
	opts: { version?: number; nameOverride?: string } = {},
): void {
	const agentsDir = join(cwd, ".pi", "agents");
	mkdirSync(agentsDir, { recursive: true });
	const version = opts.version ?? GENERATOR_VERSION;
	const nameField = opts.nameOverride ?? agentName;
	const content = [
		"---",
		`name: ${nameField}`,
		"description: test",
		"tools: read",
		"session-mode: lineage-only",
		"auto-exit: true",
		"spawning: false",
		"---",
		"",
		"# body",
		"",
		`_Generated by pi-velpari (generator v${version}) from technology resource(s): \`typescript\`._`,
		"",
	].join("\n");
	writeFileSync(join(agentsDir, `${agentName}.md`), content, "utf8");
}

function writeAgentsJson(
	cwd: string,
	agents: Record<string, string> | null,
): void {
	const dir = join(cwd, ".pi", "velpari");
	mkdirSync(dir, { recursive: true });
	if (agents === null) return;
	writeFileSync(join(dir, "agents.json"), JSON.stringify({ version: 1, agents }), "utf8");
}

describe("checkSubAgentGeneratorSection (Phase 7)", () => {
	it("returns the section title 'Sub-agent generator completeness'", () => {
		const cwd = freshTmp();
		try {
			const section = checkSubAgentGeneratorSection(cwd);
			assert.equal(section.title, "Sub-agent generator completeness");
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("bundled defaults (no agents.json) → one info item per role + summary", () => {
		const cwd = freshTmp();
		try {
			const section = checkSubAgentGeneratorSection(cwd);
			const infoMessages = section.items.filter((i) => i.status === "info").map((i) => i.message);
			// 4 roles × 1 info each = 4 info items + 1 summary info
			const roleInfo = infoMessages.filter((m) => /bundled default/.test(m));
			assert.equal(roleInfo.length, VELPARI_BRAINSTORM_GENERATED_ROLES.length);
			// Summary mentions all 4 roles
			const summary = section.items.find((i) => /Sub-agent generator summary/.test(i.message));
			assert.ok(summary, "summary item must exist");
			assert.match(summary!.message, new RegExp(`${VELPARI_BRAINSTORM_GENERATED_ROLES.length} brainstorm role`));
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("custom mapping → info per role; generator-specific checks skipped", () => {
		const cwd = freshTmp();
		try {
			// All 4 mapped to a custom name that is neither default nor generated
			writeAgentsJson(cwd, {
				extractor: "my-extractor",
				"prd-checker": "my-prd-checker",
				"rtm-checker": "my-rtm-checker",
				"web-search-agent": "my-ws",
			});
			const section = checkSubAgentGeneratorSection(cwd);
			const customInfo = section.items.filter(
				(i) => i.status === "info" && /custom mapping/.test(i.message),
			);
			assert.equal(customInfo.length, 4);
			// No errors (custom agents are user-owned; integrity is checked elsewhere)
			assert.equal(section.items.filter((i) => i.status === "error").length, 0);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with MISSING file → error per role + suggestion", () => {
		const cwd = freshTmp();
		try {
			// Map extractor to the expected generated name but don't write the file
			const slug = "velpari-doctor";
			// Force the slug via agents.json mapping
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
				"prd-checker": `${slug}-prd-checker`,
				"rtm-checker": `${slug}-rtm-checker`,
				"web-search-agent": `${slug}-web-search-agent`,
			});
			// Mock getProjectSlug by writing a package.json with the slug
			writeFileSync(
				join(cwd, "package.json"),
				JSON.stringify({ name: slug }),
				"utf8",
			);
			const section = checkSubAgentGeneratorSection(cwd);
			const errItems = section.items.filter((i) => i.status === "error");
			assert.equal(errItems.length, 4, "4 missing files → 4 errors");
			for (const err of errItems) {
				assert.match(err.message, /MISSING/);
			}
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with file present, matching frontmatter, current footer → ok", () => {
		const cwd = freshTmp();
		try {
			const slug = "demo-project";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
				"prd-checker": `${slug}-prd-checker`,
				"rtm-checker": `${slug}-rtm-checker`,
				"web-search-agent": `${slug}-web-search-agent`,
			});
			for (const role of ["extractor", "prd-checker", "rtm-checker", "web-search-agent"]) {
				writeGeneratedAgent(cwd, `${slug}-${role}`, { version: GENERATOR_VERSION });
			}
			const section = checkSubAgentGeneratorSection(cwd);
			// 4 per-role OK items. The summary item is also 'ok' when there
			// are no errors / warnings — we filter for the per-role pattern
			// ("generator v<N> OK") to exclude it.
			const perRoleOK = section.items.filter(
				(i) => i.status === "ok" && /generator v\d+ OK/.test(i.message),
			);
			assert.equal(perRoleOK.length, 4, "4 generated agents with current footer → 4 ok");
			const errors = section.items.filter((i) => i.status === "error");
			assert.equal(errors.length, 0);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with stale footer (v1 < current) → warning", () => {
		const cwd = freshTmp();
		try {
			const slug = "stale-proj";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
			});
			// Write an extractor with v0 footer (stale relative to current v1+)
			writeGeneratedAgent(cwd, `${slug}-extractor`, { version: Math.max(0, GENERATOR_VERSION - 1) });
			const section = checkSubAgentGeneratorSection(cwd);
			const warnings = section.items.filter((i) => i.status === "warning");
			assert.ok(warnings.length >= 1, "stale footer should warn");
			assert.match(warnings[0]!.message, /stale/i);
			assert.match(warnings[0]!.suggestion ?? "", /\/velpari-generate-sub-agents/);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with NEWER footer (future version) → info, not error", () => {
		const cwd = freshTmp();
		try {
			const slug = "future-proj";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
			});
			writeGeneratedAgent(cwd, `${slug}-extractor`, { version: GENERATOR_VERSION + 1 });
			const section = checkSubAgentGeneratorSection(cwd);
			const errors = section.items.filter((i) => i.status === "error");
			assert.equal(errors.length, 0, "newer footer is not an error");
			const infos = section.items.filter((i) => i.status === "info");
			assert.ok(infos.some((i) => /NEWER/.test(i.message)), "info item notes the newer version");
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with frontmatter name mismatch → error", () => {
		const cwd = freshTmp();
		try {
			const slug = "name-mismatch";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
			});
			// Write the file with a different name in frontmatter
			writeGeneratedAgent(cwd, `${slug}-extractor`, { nameOverride: "wrong-name" });
			const section = checkSubAgentGeneratorSection(cwd);
			const errItems = section.items.filter((i) => i.status === "error");
			assert.ok(errItems.some((i) => /name:/.test(i.message) || /name/.test(i.message)));
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("generated mapping with missing footer → error", () => {
		const cwd = freshTmp();
		try {
			const slug = "no-footer";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
			});
			// Write a file that lacks the footer entirely
			const agentsDir = join(cwd, ".pi", "agents");
			mkdirSync(agentsDir, { recursive: true });
			writeFileSync(
				join(agentsDir, `${slug}-extractor.md`),
				[
					"---",
					`name: ${slug}-extractor`,
					"description: no footer",
					"tools: read",
					"---",
					"",
					"# no footer",
				].join("\n"),
				"utf8",
			);
			const section = checkSubAgentGeneratorSection(cwd);
			const errItems = section.items.filter((i) => i.status === "error");
			assert.ok(
				errItems.some((i) => /missing the generator-version footer/.test(i.message)),
				`expected 'missing generator-version footer' error; got: ${errItems.map((i) => i.message).join(" | ")}`,
			);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("project-wide scan catches stale versions for non-registered roles", () => {
		const cwd = freshTmp();
		try {
			// No agents.json — no per-role items. But the project-wide scan
			// still walks .pi/agents/*.md and flags stale footers.
			const agentsDir = join(cwd, ".pi", "agents");
			mkdirSync(agentsDir, { recursive: true });
			writeFileSync(
				join(agentsDir, "unregistered-stale-agent.md"),
				[
					"---",
					"name: unregistered-stale-agent",
					"description: stale",
					"tools: read",
					"---",
					"",
					`_Generated by pi-velpari (generator v0)_`,
				].join("\n"),
				"utf8",
			);
			const section = checkSubAgentGeneratorSection(cwd);
			const warnings = section.items.filter((i) => i.status === "warning");
			assert.ok(
				warnings.some((i) => /unregistered-stale-agent\.md/.test(i.message)),
				"project-wide scan must flag stale files even when the role isn't registered",
			);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("summary item counts errors + warnings correctly", () => {
		const cwd = freshTmp();
		try {
			const slug = "summary-test";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			// 2 stale, 2 missing
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
				"prd-checker": `${slug}-prd-checker`,
				"rtm-checker": `${slug}-rtm-checker`,
				"web-search-agent": `${slug}-web-search-agent`,
			});
			writeGeneratedAgent(cwd, `${slug}-extractor`, { version: Math.max(0, GENERATOR_VERSION - 1) });
			writeGeneratedAgent(cwd, `${slug}-prd-checker`, { version: Math.max(0, GENERATOR_VERSION - 1) });
			// rtm-checker and web-search-agent files are missing → errors
			const section = checkSubAgentGeneratorSection(cwd);
			const summary = section.items.find((i) => /Sub-agent generator summary/.test(i.message));
			assert.ok(summary, "summary item present");
			assert.match(summary!.message, /2 error\(s\), 2 warning\(s\)/);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("summary status flips to 'ok' only when there are no errors AND no warnings", () => {
		const cwd = freshTmp();
		try {
			const slug = "all-ok";
			writeFileSync(join(cwd, "package.json"), JSON.stringify({ name: slug }), "utf8");
			writeAgentsJson(cwd, {
				extractor: `${slug}-extractor`,
				"prd-checker": `${slug}-prd-checker`,
				"rtm-checker": `${slug}-rtm-checker`,
				"web-search-agent": `${slug}-web-search-agent`,
			});
			for (const role of ["extractor", "prd-checker", "rtm-checker", "web-search-agent"]) {
				writeGeneratedAgent(cwd, `${slug}-${role}`, { version: GENERATOR_VERSION });
			}
			const section = checkSubAgentGeneratorSection(cwd);
			const summary = section.items.find((i) => /Sub-agent generator summary/.test(i.message));
			assert.ok(summary);
			assert.equal(summary!.status, "ok");
			assert.match(summary!.message, /0 error\(s\), 0 warning\(s\)/);
			// Per-role OK items + summary OK = 5 total OK items
			const okCount = section.items.filter((i) => i.status === "ok").length;
			assert.equal(okCount, 5, "4 per-role OK + 1 summary OK");
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});

	it("corrupt agents.json → falls back to defaults; integrity check stays alive", () => {
		const cwd = freshTmp();
		try {
			const dir = join(cwd, ".pi", "velpari");
			mkdirSync(dir, { recursive: true });
			writeFileSync(join(dir, "agents.json"), "{ not json", "utf8");
			// loadAgentConfig throws → checkRoleAgent treats it as null
			// → falls through to the "bundled default" branch (info).
			const section = checkSubAgentGeneratorSection(cwd);
			const roleInfo = section.items.filter(
				(i) => i.status === "info" && /bundled default/.test(i.message),
			);
			assert.equal(roleInfo.length, 4);
		} finally {
			rmSync(cwd, { recursive: true, force: true });
		}
	});
});

// Defensive: readFileSync is used indirectly via the doctor check; keep
// the import to avoid silent tree-shaking by the bundler.
void readFileSync;
