/**
 * Custom sub-agent roles (v1 — /velpari-generate-sub-agents --custom).
 *
 * Extends the generator with project-defined roles. Custom roles live in
 * `.pi/velpari/custom-roles.json` and are emitted by the generator
 * alongside the bundled brainstorm roles. Bundled roles (the v1
 * brainstorm set) stay in `agents-config.ts` and are immutable; custom
 * roles are editable per project.
 *
 * Same shape pattern as `agents.json`: a `_comment` header field, a
 * version, and a sparse `roles[]` array. Each role carries the same
 * fields as a `GeneratedRoleDef` (the generator's input shape), plus
 * `role` (the role id used as the file name suffix).
 *
 * Layer 0. Imports only `node:*`, `./paths.js`, `./constants.js`, and
 * `../io/atomic-write.js`. Never imports upward to ops/, stages/, ui/,
 * hooks/, commands/.
 *
 * Mirrors `agents-config.ts` for the project-config pattern.
 */

import { existsSync, readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { atomicWriteJson } from "../io/atomic-write.js";
import { findPackageRoot } from "./paths.js";
import { PATHS } from "./constants.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const CUSTOM_ROLES_FILE = "custom-roles.json";
const CUSTOM_ROLES_COMMENT =
	"Velpari config: project-defined sub-agent roles. Generated by /velpari-generate-sub-agents --custom. Hand-edit only if you know the role shape.";

/** A project-defined custom role. Same input shape as the generator's
 *  `GeneratedRoleDef`, plus `role` (the role id). */
export interface CustomRole {
	role: string;
	label: string;
	tools: string[];
	mandate: string;
	/** When the harness should spawn this agent. Becomes part of the
	 *  YAML `description:` frontmatter so the harness auto-invokes
	 *  correctly. Required — every role has one. */
	invocationHint: string;
	/** What this agent MUST NOT do, even if asked. Rendered as the
	 *  `## Out of scope` section in the body. Required — every role
	 *  has at least one entry. */
	outOfScope: string[];
	/** Optional. When set, the generator loads the file at this path
	 *  (relative to the agents source directory) and uses ITS content
	 *  as the agent body — replacing the standard mandate + outOfScope
	 *  + completion contract template. */
	bodyFile?: string;
	/** Optional. Marks the role as interactive (pauses for user input). */
	interactive?: boolean;
}

/** The custom-roles.json shape. */
export interface CustomRolesConfig {
	version: 1;
	roles: CustomRole[];
}

/** Absolute path to `.pi/velpari/custom-roles.json` for the given project root. */
export function getCustomRolesPath(cwd: string): string {
	return join(cwd, PATHS.CONFIG_DIR, CUSTOM_ROLES_FILE);
}

/** Validate a single CustomRole. Throws with a descriptive message on the
 *  first error. Returns the role on success. */
export function validateCustomRole(role: CustomRole): CustomRole {
	if (typeof role.role !== "string" || !role.role.trim()) {
		throw new Error("CustomRole.role must be a non-empty string");
	}
	if (typeof role.label !== "string" || !role.label.trim()) {
		throw new Error(`CustomRole[${role.role}].label must be a non-empty string`);
	}
	if (!Array.isArray(role.tools) || role.tools.some((t) => typeof t !== "string")) {
		throw new Error(`CustomRole[${role.role}].tools must be an array of strings`);
	}
	if (typeof role.mandate !== "string" || !role.mandate.trim()) {
		throw new Error(`CustomRole[${role.role}].mandate must be a non-empty string`);
	}
	if (typeof role.invocationHint !== "string" || !role.invocationHint.trim()) {
		throw new Error(`CustomRole[${role.role}].invocationHint must be a non-empty string`);
	}
	if (!Array.isArray(role.outOfScope) || role.outOfScope.some((o) => typeof o !== "string")) {
		throw new Error(`CustomRole[${role.role}].outOfScope must be an array of strings`);
	}
	if (role.bodyFile !== undefined && typeof role.bodyFile !== "string") {
		throw new Error(`CustomRole[${role.role}].bodyFile must be a string when present`);
	}
	if (role.interactive !== undefined && typeof role.interactive !== "boolean") {
		throw new Error(`CustomRole[${role.role}].interactive must be a boolean when present`);
	}
	return role;
}

/** Validate a CustomRolesConfig. Throws with descriptive errors. */
export function validateCustomRoles(config: CustomRolesConfig): CustomRolesConfig {
	if (config.version !== 1) {
		throw new Error("Missing or invalid 'version' field (expected 1)");
	}
	if (!Array.isArray(config.roles)) {
		throw new Error("Missing or invalid 'roles' field (expected an array)");
	}
	const seen = new Set<string>();
	for (const role of config.roles) {
		validateCustomRole(role);
		if (seen.has(role.role)) {
			throw new Error(`Duplicate role id "${role.role}" in custom-roles.json`);
		}
		seen.add(role.role);
	}
	return config;
}

/** Load custom-roles.json. Returns null when the file is missing (absence
 *  means "no custom roles"). Throws `Invalid custom-roles config at
 *  <path>: ...` on bad JSON, wrong version, missing fields, or
 *  duplicate role ids. The `_comment` field is stripped before
 *  validation. */
export function loadCustomRoles(cwd: string): CustomRolesConfig | null {
	const configPath = getCustomRolesPath(cwd);
	let raw: string;
	try {
		raw = readFileSync(configPath, "utf8");
	} catch (err) {
		if ((err as NodeJS.ErrnoException).code === "ENOENT") return null;
		throw new Error(`Invalid custom-roles config at ${configPath}: ${(err as Error).message}`);
	}
	let parsed: CustomRolesConfig;
	try {
		parsed = JSON.parse(raw) as CustomRolesConfig;
		delete (parsed as unknown as Record<string, unknown>)._comment;
		validateCustomRoles(parsed);
	} catch (err) {
		throw new Error(`Invalid custom-roles config at ${configPath}: ${(err as Error).message}`);
	}
	return parsed;
}

/** Save custom-roles.json atomically with the `_comment` header. */
export function saveCustomRoles(cwd: string, config: CustomRolesConfig): void {
	atomicWriteJson(getCustomRolesPath(cwd), { _comment: CUSTOM_ROLES_COMMENT, ...config });
}

/** Look up the bundled custom-roles starter file shipped with the extension.
 *  Returns the parsed CustomRolesConfig. Throws if the bundle is missing
 *  or malformed (this would be a packaging defect). */
export function getBundledCustomRoles(): CustomRolesConfig {
	const pkgRoot = findPackageRoot(__dirname);
	const candidates = [
		join(pkgRoot, "pi-extension", "src", "core", "bundled-custom-roles.json"),
		join(pkgRoot, "dist", "pi-extension", "src", "core", "bundled-custom-roles.json"),
	];
	let raw: string | null = null;
	for (const p of candidates) {
		if (existsSync(p)) {
			raw = readFileSync(p, "utf8");
			break;
		}
	}
	if (raw === null) {
		throw new Error(
			`Bundled custom-roles starter not found. Searched: ${candidates.join(", ")}`,
		);
	}
	const parsed = JSON.parse(raw) as CustomRolesConfig;
	delete (parsed as unknown as Record<string, unknown>)._comment;
	validateCustomRoles(parsed);
	return parsed;
}

/** Find a custom role by its role id. Returns null when not found.
 *  Reads the project's `.pi/velpari/custom-roles.json` (or null when absent). */
export function findCustomRole(cwd: string, roleId: string): CustomRole | null {
	const config = loadCustomRoles(cwd);
	if (!config) return null;
	return config.roles.find((r) => r.role === roleId) ?? null;
}

/** All custom-role ids in the project's custom-roles.json. Returns []
 *  when the file is missing. */
export function listCustomRoleIds(cwd: string): string[] {
	const config = loadCustomRoles(cwd);
	if (!config) return [];
	return config.roles.map((r) => r.role);
}