/**
 * generated-files doctor check tests (Phase C, plan Subphase 2.6 — G4).
 *
 * Covers: corrupt manifest (file exists, loader returns empty) → warning;
 * no manifest → info; manifest entry with no file → error missing;
 * hash drift → warning modified; agent .md missing frontmatter fields →
 * error bad-config; footer-marked file absent from manifest → warning
 * unregistered; clean tracked file → ok.
 *
 * Manifests are written directly as `{version:1, files:{rel: sha256}}`
 * (the exact `core/generated-manifest.ts` shape).
 */

import { afterEach, beforeEach, describe, it } from "node:test";
import { strict as assert } from "node:assert";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

import { checkGeneratedFilesSection } from "../../../src/doctor/checks/generated-files.js";
import { hashFileContent } from "../../../src/core/fingerprints.js";

let tmpDir: string;

beforeEach(() => {
	tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), "velpari-generated-files-"));
});

afterEach(() => {
	fs.rmSync(tmpDir, { recursive: true, force: true });
});

/** Write a file under the fixture root (parent dirs created). */
function put(rel: string, content: string): string {
	const abs = path.join(tmpDir, rel);
	fs.mkdirSync(path.dirname(abs), { recursive: true });
	fs.writeFileSync(abs, content, "utf8");
	return abs;
}

/** Write the manifest in the exact core/generated-manifest.ts shape. */
function writeManifest(files: Record<string, string>): void {
	put(".pi/velpari/generated-manifest.json", JSON.stringify({ version: 1, files }, null, "\t"));
}

describe("checkGeneratedFilesSection", () => {
	it("no manifest → info (nothing tracked yet)", () => {
		const section = checkGeneratedFilesSection(tmpDir);
		assert.equal(section.title, "Newly generated files (generated-manifest validation)");
		assert.equal(section.items[0]?.status, "info");
		assert.match(section.items[0]!.message, /No generated files tracked yet/);
	});

	it("corrupt manifest file → warning generated-manifest-unreadable", () => {
		put(".pi/velpari/generated-manifest.json", "{ not json at all");
		const section = checkGeneratedFilesSection(tmpDir);
		const warn = section.items.find((i) => i.status === "warning");
		assert.ok(warn, "expected a warning");
		assert.match(warn!.message, /generated-manifest-unreadable/);
		// The corrupt-manifest warning must not be doubled by the info line.
		assert.ok(!section.items.some((i) => i.message.includes("No generated files tracked yet")));
	});

	it("manifest entry with no file → error generated-file-missing", () => {
		writeManifest({ ".pi/agents/ghost.md": "a".repeat(64) });
		const section = checkGeneratedFilesSection(tmpDir);
		const err = section.items.find((i) => i.status === "error");
		assert.ok(err, "expected an error");
		assert.match(err!.message, /generated-file-missing: \.pi\/agents\/ghost\.md/);
	});

	it("non-agent file hash drift → warning generated-file-modified", () => {
		const abs = put("skills/generated-thing.md", "# v1\n");
		const sha = hashFileContent(abs)!;
		writeManifest({ "skills/generated-thing.md": sha });
		put("skills/generated-thing.md", "# v2 — edited after generation\n");

		const section = checkGeneratedFilesSection(tmpDir);
		const warn = section.items.find((i) => i.status === "warning");
		assert.ok(warn, "expected a warning");
		assert.match(warn!.message, /generated-file-modified/);
		assert.ok(warn!.details?.some((d) => d.startsWith("manifest sha256:")));
		assert.ok(warn!.details?.some((d) => d.startsWith("current  sha256:")));
	});

	it("agent .md with missing frontmatter fields → error generated-file-bad-config", () => {
		const abs = put(".pi/agents/my-role.md", "# No frontmatter here\n");
		const sha = hashFileContent(abs)!;
		writeManifest({ ".pi/agents/my-role.md": sha });

		const section = checkGeneratedFilesSection(tmpDir);
		const err = section.items.find((i) => i.status === "error");
		assert.ok(err, "expected an error");
		assert.match(err!.message, /generated-file-bad-config/);
		assert.match(err!.message, /missing\/invalid frontmatter field/);
		assert.match(err!.message, /name/);
	});

	it("footer-marked agent absent from manifest → warning generated-file-unregistered", () => {
		const abs = put("skills/tracked.md", "# tracked\n");
		writeManifest({ "skills/tracked.md": hashFileContent(abs)! });
		put(
			".pi/agents/stray-role.md",
			"# Stray\n\n_Generated by pi-velpari (generator v7) from canonical body file: x.md._\n",
		);

		const section = checkGeneratedFilesSection(tmpDir);
		const warn = section.items.find((i) => i.message.includes("generated-file-unregistered"));
		assert.ok(warn, "expected unregistered warning");
		assert.equal(warn!.status, "warning");
		assert.match(warn!.message, /\.pi\/agents\/stray-role\.md/);
	});

	it("clean tracked file (non-agent) → ok", () => {
		const abs = put("skills/generated-thing.md", "# v1\n");
		writeManifest({ "skills/generated-thing.md": hashFileContent(abs)! });

		const section = checkGeneratedFilesSection(tmpDir);
		assert.equal(section.items[0]?.status, "ok");
		assert.match(section.items[0]!.message, /1 generated file\(s\) verified against the manifest/);
	});

	it("agent .md with full frontmatter + matching hash → no bad-config", () => {
		const content = [
			"---",
			"name: my-role",
			"description: A role",
			"tools: read, bash",
			"thinking: medium",
			"session-mode: fork",
			"auto-exit: true",
			"spawning: spawn-ok",
			"---",
			"# Role",
			"",
			"_Generated by pi-velpari (generator v7) from canonical body file: x.md._",
		].join("\n");
		const abs = put(".pi/agents/my-role.md", content);
		writeManifest({ ".pi/agents/my-role.md": hashFileContent(abs)! });

		const section = checkGeneratedFilesSection(tmpDir);
		assert.equal(section.items[0]?.status, "ok");
	});

	it("never throws (doctor always renders)", () => {
		put(".pi/velpari/generated-manifest.json", "[]"); // wrong shape → fail-open
		const section = checkGeneratedFilesSection(tmpDir);
		assert.ok(section.items.length > 0);
	});
});
